# Generated by Django 4.0.3 on 2022-03-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Name')),
                ('last_name', models.CharField(max_length=15, verbose_name='Last name')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone #')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('available', models.IntegerField(verbose_name='Available units')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.cart', verbose_name='Cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='Choosen',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('total', models.FloatField(verbose_name='Total Price')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.cart', verbose_name='Cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.item', verbose_name='Item')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.customer'),
        ),
    ]
