# Generated by Django 4.0.3 on 2022-04-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_cart_customer_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Name')),
                ('last_name', models.CharField(max_length=15, verbose_name='Last name')),
                ('email', models.EmailField(max_length=25, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone #')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.customer'),
        ),
    ]
