# Generated by Django 4.0.3 on 2022-04-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_cart_customer_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosen',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
