# Generated by Django 4.0.3 on 2022-04-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_choosen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosen',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
