# Generated by Django 4.0.3 on 2022-04-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_cart_id_alter_category_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default=[], max_length=2000, verbose_name='Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.IntegerField(verbose_name='Cart'),
        ),
    ]
